baseURL = "https://burakgizlice.com/"
languageCode = "en-us"
title = "Burak Gizlice"
theme = "quint"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

paginate = 6
summaryLength = 30

[taxonomies]
  tag = "tags"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  numImages = 10
  useToc = true
  authorName = "Burak Gizlice"
  authorImage = "https://github.com/burakgizlice.png"
  contact = "You can write me an [email](mailto:gizliceburak@gmail.com)."

  [params.giscus]
    repo = "burakgizlice/burakgizlice.com"
    repoId = "R_kgDORn05og"
    category = "General"
    categoryId = "DIC_kwDORn05os4C4d3f"
    mapping = "pathname"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "https://burakgizlice.com/css/giscus-custom.css"
    lang = "en"

  [[params.social]]
    url = "https://linkedin.com/in/burakgizlice"
    icon = "/social/linkedin.svg"
    name = "LinkedIn"

  [[params.social]]
    url = "https://github.com/burakgizlice"
    icon = "/social/github.svg"
    name = "GitHub"

  [[params.social]]
    url = "https://medium.com/@burakgizlice"
    icon = "/social/medium.svg"
    name = "Medium"

  [[params.social]]
    url = "mailto:gizliceburak@gmail.com"
    icon = "/social/email.png"
    name = "Email"

